from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(916, 600)
        MainWindow.setStyleSheet("*{\n"
                                 "    border:none;\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        self.header_frame.setStyleSheet("background-color: #7D7C7C;")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.header_left_frame = QtWidgets.QFrame(self.header_frame)
        self.header_left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_left_frame.setObjectName("header_left_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.header_left_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menu_button = QtWidgets.QPushButton(self.header_left_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.menu_button.setFont(font)
        self.menu_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-menu-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_button.setIcon(icon)
        self.menu_button.setIconSize(QtCore.QSize(50, 50))
        self.menu_button.setObjectName("menu_button")
        self.horizontalLayout_4.addWidget(self.menu_button)
        self.menu_label = QtWidgets.QLabel(self.header_left_frame)
        self.menu_label.setMinimumSize(QtCore.QSize(0, 0))
        self.menu_label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.menu_label.setFont(font)
        self.menu_label.setObjectName("menu_label")
        self.horizontalLayout_4.addWidget(self.menu_label)
        self.horizontalLayout.addWidget(self.header_left_frame, 0, QtCore.Qt.AlignLeft)
        self.header_central_frame = QtWidgets.QFrame(self.header_frame)
        self.header_central_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_central_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_central_frame.setObjectName("header_central_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.header_central_frame)
        self.horizontalLayout_3.setContentsMargins(15, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.app_logo_label = QtWidgets.QLabel(self.header_central_frame)
        font = QtGui.QFont()
        font.setPointSize(5)
        self.app_logo_label.setFont(font)
        self.app_logo_label.setText("")
        self.app_logo_label.setPixmap(QtGui.QPixmap(":/icons/icons/icons8-database-view-30.png"))
        self.app_logo_label.setObjectName("app_logo_label")
        self.horizontalLayout_3.addWidget(self.app_logo_label, 0, QtCore.Qt.AlignRight)
        self.app_name_label = QtWidgets.QLabel(self.header_central_frame)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.app_name_label.setFont(font)
        self.app_name_label.setObjectName("app_name_label")
        self.horizontalLayout_3.addWidget(self.app_name_label)
        self.horizontalLayout.addWidget(self.header_central_frame, 0, QtCore.Qt.AlignHCenter)
        self.header_right_frame = QtWidgets.QFrame(self.header_frame)
        self.header_right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_right_frame.setObjectName("header_right_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header_right_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.window_minimize_button = QtWidgets.QPushButton(self.header_right_frame)
        self.window_minimize_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-subtract-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.window_minimize_button.setIcon(icon1)
        self.window_minimize_button.setObjectName("window_minimize_button")
        self.horizontalLayout_2.addWidget(self.window_minimize_button)
        self.window_restore_button = QtWidgets.QPushButton(self.header_right_frame)
        self.window_restore_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-maximize-button-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.window_restore_button.setIcon(icon2)
        self.window_restore_button.setObjectName("window_restore_button")
        self.horizontalLayout_2.addWidget(self.window_restore_button)
        self.window_close_button = QtWidgets.QPushButton(self.header_right_frame)
        self.window_close_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-close-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.window_close_button.setIcon(icon3)
        self.window_close_button.setObjectName("window_close_button")
        self.horizontalLayout_2.addWidget(self.window_close_button)
        self.horizontalLayout.addWidget(self.header_right_frame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.header_frame, 0, QtCore.Qt.AlignTop)
        self.central_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.central_frame.sizePolicy().hasHeightForWidth())
        self.central_frame.setSizePolicy(sizePolicy)
        self.central_frame.setStyleSheet("background-color: #69676A;")
        self.central_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.central_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.central_frame.setObjectName("central_frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.central_frame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.left_menu_content_frame = QtWidgets.QFrame(self.central_frame)
        self.left_menu_content_frame.setMinimumSize(QtCore.QSize(50, 0))
        self.left_menu_content_frame.setMaximumSize(QtCore.QSize(50, 16777215))
        self.left_menu_content_frame.setStyleSheet("background-color: #737171;")
        self.left_menu_content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_content_frame.setObjectName("left_menu_content_frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.left_menu_content_frame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.menu_frame = QtWidgets.QFrame(self.left_menu_content_frame)
        self.menu_frame.setMinimumSize(QtCore.QSize(90, 0))
        self.menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.menu_frame)
        self.gridLayout.setContentsMargins(10, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.schedule_button = QtWidgets.QPushButton(self.menu_frame)
        self.schedule_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-timesheet-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.schedule_button.setIcon(icon4)
        self.schedule_button.setIconSize(QtCore.QSize(35, 35))
        self.schedule_button.setObjectName("schedule_button")
        self.gridLayout.addWidget(self.schedule_button, 7, 0, 1, 1)
        self.category_button = QtWidgets.QPushButton(self.menu_frame)
        self.category_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-category-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.category_button.setIcon(icon5)
        self.category_button.setIconSize(QtCore.QSize(35, 35))
        self.category_button.setObjectName("category_button")
        self.gridLayout.addWidget(self.category_button, 5, 0, 1, 1)
        self.subject_button = QtWidgets.QPushButton(self.menu_frame)
        self.subject_button.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-subject-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.subject_button.setIcon(icon6)
        self.subject_button.setIconSize(QtCore.QSize(35, 35))
        self.subject_button.setObjectName("subject_button")
        self.gridLayout.addWidget(self.subject_button, 6, 0, 1, 1)
        self.student_label = QtWidgets.QLabel(self.menu_frame)
        self.student_label.setObjectName("student_label")
        self.gridLayout.addWidget(self.student_label, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.student_button = QtWidgets.QPushButton(self.menu_frame)
        self.student_button.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-student-male-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.student_button.setIcon(icon7)
        self.student_button.setIconSize(QtCore.QSize(35, 35))
        self.student_button.setObjectName("student_button")
        self.gridLayout.addWidget(self.student_button, 0, 0, 1, 1)
        self.instructor_button = QtWidgets.QPushButton(self.menu_frame)
        self.instructor_button.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-personal-trainer-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.instructor_button.setIcon(icon8)
        self.instructor_button.setIconSize(QtCore.QSize(35, 35))
        self.instructor_button.setObjectName("instructor_button")
        self.gridLayout.addWidget(self.instructor_button, 3, 0, 1, 1)
        self.staff_button = QtWidgets.QPushButton(self.menu_frame)
        self.staff_button.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-staff-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.staff_button.setIcon(icon9)
        self.staff_button.setIconSize(QtCore.QSize(35, 35))
        self.staff_button.setObjectName("staff_button")
        self.gridLayout.addWidget(self.staff_button, 2, 0, 1, 1)
        self.group_button = QtWidgets.QPushButton(self.menu_frame)
        self.group_button.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-group-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.group_button.setIcon(icon10)
        self.group_button.setIconSize(QtCore.QSize(35, 35))
        self.group_button.setObjectName("group_button")
        self.gridLayout.addWidget(self.group_button, 1, 0, 1, 1)
        self.audienc_button = QtWidgets.QPushButton(self.menu_frame)
        self.audienc_button.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-classroom-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.audienc_button.setIcon(icon11)
        self.audienc_button.setIconSize(QtCore.QSize(35, 35))
        self.audienc_button.setObjectName("audienc_button")
        self.gridLayout.addWidget(self.audienc_button, 4, 0, 1, 1)
        self.group_label = QtWidgets.QLabel(self.menu_frame)
        self.group_label.setObjectName("group_label")
        self.gridLayout.addWidget(self.group_label, 1, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.staff_label = QtWidgets.QLabel(self.menu_frame)
        self.staff_label.setObjectName("staff_label")
        self.gridLayout.addWidget(self.staff_label, 2, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.instructor_label = QtWidgets.QLabel(self.menu_frame)
        self.instructor_label.setObjectName("instructor_label")
        self.gridLayout.addWidget(self.instructor_label, 3, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.audience_label = QtWidgets.QLabel(self.menu_frame)
        self.audience_label.setObjectName("audience_label")
        self.gridLayout.addWidget(self.audience_label, 4, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.category_label = QtWidgets.QLabel(self.menu_frame)
        self.category_label.setObjectName("category_label")
        self.gridLayout.addWidget(self.category_label, 5, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.subject_label = QtWidgets.QLabel(self.menu_frame)
        self.subject_label.setObjectName("subject_label")
        self.gridLayout.addWidget(self.subject_label, 6, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.schedule_label = QtWidgets.QLabel(self.menu_frame)
        self.schedule_label.setObjectName("schedule_label")
        self.gridLayout.addWidget(self.schedule_label, 7, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.horizontalLayout_9.addWidget(self.menu_frame, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.horizontalLayout_8.addWidget(self.left_menu_content_frame)
        self.main_body_frame = QtWidgets.QFrame(self.central_frame)
        self.main_body_frame.setStyleSheet("background-color: #3E3D3E;")
        self.main_body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body_frame.setObjectName("main_body_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.main_body_frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_body_frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.students = QtWidgets.QWidget()
        self.students.setObjectName("students")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.students)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.student_upper_frame = QtWidgets.QFrame(self.students)
        self.student_upper_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.student_upper_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.student_upper_frame.setObjectName("student_upper_frame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.student_upper_frame)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.student_window_label = QtWidgets.QLabel(self.student_upper_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.student_window_label.setFont(font)
        self.student_window_label.setObjectName("student_window_label")
        self.horizontalLayout_12.addWidget(self.student_window_label)
        self.student_search_frame = QtWidgets.QFrame(self.student_upper_frame)
        self.student_search_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.student_search_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.student_search_frame.setObjectName("student_search_frame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.student_search_frame)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.student_lineEdit = QtWidgets.QLineEdit(self.student_search_frame)
        self.student_lineEdit.setStyleSheet("background-color: #69676A;")
        self.student_lineEdit.setObjectName("student_lineEdit")
        self.horizontalLayout_13.addWidget(self.student_lineEdit)
        self.student_search_button = QtWidgets.QPushButton(self.student_search_frame)
        self.student_search_button.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-search-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.student_search_button.setIcon(icon12)
        self.student_search_button.setObjectName("student_search_button")
        self.horizontalLayout_13.addWidget(self.student_search_button)
        self.horizontalLayout_12.addWidget(self.student_search_frame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_6.addWidget(self.student_upper_frame, 0, QtCore.Qt.AlignTop)
        self.student_central_frame = QtWidgets.QFrame(self.students)
        self.student_central_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.student_central_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.student_central_frame.setObjectName("student_central_frame")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.student_central_frame)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.student_tableWidget = QtWidgets.QTableWidget(self.student_central_frame)
        self.student_tableWidget.setObjectName("student_tableWidget")
        self.student_tableWidget.setColumnCount(9)
        self.student_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.student_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.student_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.student_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.student_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.student_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.student_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.student_tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.student_tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.student_tableWidget.setHorizontalHeaderItem(8, item)
        self.horizontalLayout_15.addWidget(self.student_tableWidget)
        self.verticalLayout_6.addWidget(self.student_central_frame)
        self.student_lower_frame = QtWidgets.QFrame(self.students)
        self.student_lower_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.student_lower_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.student_lower_frame.setObjectName("student_lower_frame")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.student_lower_frame)
        self.horizontalLayout_14.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_14.setSpacing(50)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.student_replace_button = QtWidgets.QPushButton(self.student_lower_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.student_replace_button.setFont(font)
        self.student_replace_button.setStyleSheet("background-color: #202020;")
        self.student_replace_button.setObjectName("student_replace_button")
        self.horizontalLayout_14.addWidget(self.student_replace_button, 0, QtCore.Qt.AlignRight)
        self.student_add_button = QtWidgets.QPushButton(self.student_lower_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.student_add_button.setFont(font)
        self.student_add_button.setStyleSheet("background-color: #202020;")
        self.student_add_button.setObjectName("student_add_button")
        self.horizontalLayout_14.addWidget(self.student_add_button, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_6.addWidget(self.student_lower_frame, 0, QtCore.Qt.AlignBottom)
        self.stackedWidget.addWidget(self.students)
        self.groups = QtWidgets.QWidget()
        self.groups.setObjectName("groups")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groups)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.group_upper_frame = QtWidgets.QFrame(self.groups)
        self.group_upper_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.group_upper_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.group_upper_frame.setObjectName("group_upper_frame")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.group_upper_frame)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.group_window_label = QtWidgets.QLabel(self.group_upper_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.group_window_label.setFont(font)
        self.group_window_label.setObjectName("group_window_label")
        self.horizontalLayout_17.addWidget(self.group_window_label)
        self.group_search_frame = QtWidgets.QFrame(self.group_upper_frame)
        self.group_search_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.group_search_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.group_search_frame.setObjectName("group_search_frame")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.group_search_frame)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.group_lineEdit = QtWidgets.QLineEdit(self.group_search_frame)
        self.group_lineEdit.setStyleSheet("background-color: #69676A;")
        self.group_lineEdit.setObjectName("group_lineEdit")
        self.horizontalLayout_16.addWidget(self.group_lineEdit)
        self.group_search_button = QtWidgets.QPushButton(self.group_search_frame)
        self.group_search_button.setText("")
        self.group_search_button.setIcon(icon12)
        self.group_search_button.setObjectName("group_search_button")
        self.horizontalLayout_16.addWidget(self.group_search_button)
        self.horizontalLayout_17.addWidget(self.group_search_frame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_7.addWidget(self.group_upper_frame, 0, QtCore.Qt.AlignTop)
        self.group_central_frame = QtWidgets.QFrame(self.groups)
        self.group_central_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.group_central_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.group_central_frame.setObjectName("group_central_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.group_central_frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.group_tableWidget = QtWidgets.QTableWidget(self.group_central_frame)
        self.group_tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.group_tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.group_tableWidget.setLineWidth(1)
        self.group_tableWidget.setIconSize(QtCore.QSize(0, 0))
        self.group_tableWidget.setShowGrid(True)
        self.group_tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.group_tableWidget.setWordWrap(True)
        self.group_tableWidget.setRowCount(0)
        self.group_tableWidget.setObjectName("group_tableWidget")
        self.group_tableWidget.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.group_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.group_tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_8.addWidget(self.group_tableWidget)
        self.verticalLayout_7.addWidget(self.group_central_frame)
        self.group_lower_frame = QtWidgets.QFrame(self.groups)
        self.group_lower_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.group_lower_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.group_lower_frame.setObjectName("group_lower_frame")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.group_lower_frame)
        self.horizontalLayout_18.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_18.setSpacing(50)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.group_replace_button = QtWidgets.QPushButton(self.group_lower_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.group_replace_button.setFont(font)
        self.group_replace_button.setStyleSheet("background-color: #202020;")
        self.group_replace_button.setObjectName("group_replace_button")
        self.horizontalLayout_18.addWidget(self.group_replace_button, 0, QtCore.Qt.AlignRight)
        self.group_add_button = QtWidgets.QPushButton(self.group_lower_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.group_add_button.setFont(font)
        self.group_add_button.setStyleSheet("background-color: #202020;")
        self.group_add_button.setObjectName("group_add_button")
        self.horizontalLayout_18.addWidget(self.group_add_button, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_7.addWidget(self.group_lower_frame, 0, QtCore.Qt.AlignBottom)
        self.stackedWidget.addWidget(self.groups)
        self.staff = QtWidgets.QWidget()
        self.staff.setObjectName("staff")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.staff)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.staff_upper_frame = QtWidgets.QFrame(self.staff)
        self.staff_upper_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.staff_upper_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.staff_upper_frame.setObjectName("staff_upper_frame")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.staff_upper_frame)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.staff_window_label = QtWidgets.QLabel(self.staff_upper_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.staff_window_label.setFont(font)
        self.staff_window_label.setObjectName("staff_window_label")
        self.horizontalLayout_20.addWidget(self.staff_window_label)
        self.staff_search_frame = QtWidgets.QFrame(self.staff_upper_frame)
        self.staff_search_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.staff_search_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.staff_search_frame.setObjectName("staff_search_frame")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.staff_search_frame)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.staff_lineEdit = QtWidgets.QLineEdit(self.staff_search_frame)
        self.staff_lineEdit.setStyleSheet("background-color: #69676A;")
        self.staff_lineEdit.setObjectName("staff_lineEdit")
        self.horizontalLayout_19.addWidget(self.staff_lineEdit)
        self.staff_search_button = QtWidgets.QPushButton(self.staff_search_frame)
        self.staff_search_button.setText("")
        self.staff_search_button.setIcon(icon12)
        self.staff_search_button.setObjectName("staff_search_button")
        self.horizontalLayout_19.addWidget(self.staff_search_button)
        self.horizontalLayout_20.addWidget(self.staff_search_frame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_9.addWidget(self.staff_upper_frame, 0, QtCore.Qt.AlignTop)
        self.staff_central_frame = QtWidgets.QFrame(self.staff)
        self.staff_central_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.staff_central_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.staff_central_frame.setObjectName("staff_central_frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.staff_central_frame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.staff_tableWidget = QtWidgets.QTableWidget(self.staff_central_frame)
        self.staff_tableWidget.setObjectName("staff_tableWidget")
        self.staff_tableWidget.setColumnCount(9)
        self.staff_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.staff_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.staff_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.staff_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.staff_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.staff_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.staff_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.staff_tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.staff_tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.staff_tableWidget.setHorizontalHeaderItem(8, item)
        self.verticalLayout_10.addWidget(self.staff_tableWidget)
        self.verticalLayout_9.addWidget(self.staff_central_frame)
        self.staff_lower_frame = QtWidgets.QFrame(self.staff)
        self.staff_lower_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.staff_lower_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.staff_lower_frame.setObjectName("staff_lower_frame")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.staff_lower_frame)
        self.horizontalLayout_21.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_21.setSpacing(50)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.staff_replace_button = QtWidgets.QPushButton(self.staff_lower_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.staff_replace_button.setFont(font)
        self.staff_replace_button.setStyleSheet("background-color: #202020;")
        self.staff_replace_button.setObjectName("staff_replace_button")
        self.horizontalLayout_21.addWidget(self.staff_replace_button, 0, QtCore.Qt.AlignRight)
        self.staff_add_button = QtWidgets.QPushButton(self.staff_lower_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.staff_add_button.setFont(font)
        self.staff_add_button.setStyleSheet("background-color: #202020;")
        self.staff_add_button.setObjectName("staff_add_button")
        self.horizontalLayout_21.addWidget(self.staff_add_button, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_9.addWidget(self.staff_lower_frame, 0, QtCore.Qt.AlignBottom)
        self.stackedWidget.addWidget(self.staff)
        self.instructors = QtWidgets.QWidget()
        self.instructors.setObjectName("instructors")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.instructors)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.instructor_upper_frame = QtWidgets.QFrame(self.instructors)
        self.instructor_upper_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.instructor_upper_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.instructor_upper_frame.setObjectName("instructor_upper_frame")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.instructor_upper_frame)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.instructor_window_label = QtWidgets.QLabel(self.instructor_upper_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.instructor_window_label.setFont(font)
        self.instructor_window_label.setObjectName("instructor_window_label")
        self.horizontalLayout_23.addWidget(self.instructor_window_label)
        self.instructor_search_frame = QtWidgets.QFrame(self.instructor_upper_frame)
        self.instructor_search_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.instructor_search_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.instructor_search_frame.setObjectName("instructor_search_frame")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.instructor_search_frame)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.instructor_lineEdit = QtWidgets.QLineEdit(self.instructor_search_frame)
        self.instructor_lineEdit.setStyleSheet("background-color: #69676A;")
        self.instructor_lineEdit.setObjectName("instructor_lineEdit")
        self.horizontalLayout_22.addWidget(self.instructor_lineEdit)
        self.instructor_search_button = QtWidgets.QPushButton(self.instructor_search_frame)
        self.instructor_search_button.setText("")
        self.instructor_search_button.setIcon(icon12)
        self.instructor_search_button.setObjectName("instructor_search_button")
        self.horizontalLayout_22.addWidget(self.instructor_search_button)
        self.horizontalLayout_23.addWidget(self.instructor_search_frame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_11.addWidget(self.instructor_upper_frame, 0, QtCore.Qt.AlignTop)
        self.instructor_central_frame = QtWidgets.QFrame(self.instructors)
        self.instructor_central_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.instructor_central_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.instructor_central_frame.setObjectName("instructor_central_frame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.instructor_central_frame)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.instructor_tableWidget = QtWidgets.QTableWidget(self.instructor_central_frame)
        self.instructor_tableWidget.setObjectName("instructor_tableWidget")
        self.instructor_tableWidget.setColumnCount(4)
        self.instructor_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.instructor_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.instructor_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.instructor_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.instructor_tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout_12.addWidget(self.instructor_tableWidget)
        self.verticalLayout_11.addWidget(self.instructor_central_frame)
        self.instructor_lower_frame = QtWidgets.QFrame(self.instructors)
        self.instructor_lower_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.instructor_lower_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.instructor_lower_frame.setObjectName("instructor_lower_frame")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.instructor_lower_frame)
        self.horizontalLayout_24.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_24.setSpacing(50)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.instructor_replace_button = QtWidgets.QPushButton(self.instructor_lower_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.instructor_replace_button.setFont(font)
        self.instructor_replace_button.setStyleSheet("background-color: #202020;")
        self.instructor_replace_button.setObjectName("instructor_replace_button")
        self.horizontalLayout_24.addWidget(self.instructor_replace_button, 0, QtCore.Qt.AlignRight)
        self.instructor_add_button = QtWidgets.QPushButton(self.instructor_lower_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.instructor_add_button.setFont(font)
        self.instructor_add_button.setStyleSheet("background-color: #202020;")
        self.instructor_add_button.setObjectName("instructor_add_button")
        self.horizontalLayout_24.addWidget(self.instructor_add_button, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_11.addWidget(self.instructor_lower_frame, 0, QtCore.Qt.AlignBottom)
        self.stackedWidget.addWidget(self.instructors)
        self.audiences = QtWidgets.QWidget()
        self.audiences.setObjectName("audiences")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.audiences)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.audience_upper_frame = QtWidgets.QFrame(self.audiences)
        self.audience_upper_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.audience_upper_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.audience_upper_frame.setObjectName("audience_upper_frame")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.audience_upper_frame)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.audience_window_label = QtWidgets.QLabel(self.audience_upper_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.audience_window_label.setFont(font)
        self.audience_window_label.setObjectName("audience_window_label")
        self.horizontalLayout_26.addWidget(self.audience_window_label)
        self.audience_search_frame = QtWidgets.QFrame(self.audience_upper_frame)
        self.audience_search_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.audience_search_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.audience_search_frame.setObjectName("audience_search_frame")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.audience_search_frame)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.audience_lineEdit = QtWidgets.QLineEdit(self.audience_search_frame)
        self.audience_lineEdit.setStyleSheet("background-color: #69676A;")
        self.audience_lineEdit.setObjectName("audience_lineEdit")
        self.horizontalLayout_25.addWidget(self.audience_lineEdit)
        self.audience_search_button = QtWidgets.QPushButton(self.audience_search_frame)
        self.audience_search_button.setText("")
        self.audience_search_button.setIcon(icon12)
        self.audience_search_button.setObjectName("audience_search_button")
        self.horizontalLayout_25.addWidget(self.audience_search_button)
        self.horizontalLayout_26.addWidget(self.audience_search_frame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_13.addWidget(self.audience_upper_frame, 0, QtCore.Qt.AlignTop)
        self.audience_central_frame = QtWidgets.QFrame(self.audiences)
        self.audience_central_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.audience_central_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.audience_central_frame.setObjectName("audience_central_frame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.audience_central_frame)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.audience_tableWidget = QtWidgets.QTableWidget(self.audience_central_frame)
        self.audience_tableWidget.setObjectName("audience_tableWidget")
        self.audience_tableWidget.setColumnCount(4)
        self.audience_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.audience_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.audience_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.audience_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.audience_tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout_14.addWidget(self.audience_tableWidget)
        self.verticalLayout_13.addWidget(self.audience_central_frame)
        self.audience_lower_frame = QtWidgets.QFrame(self.audiences)
        self.audience_lower_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.audience_lower_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.audience_lower_frame.setObjectName("audience_lower_frame")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.audience_lower_frame)
        self.horizontalLayout_27.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_27.setSpacing(50)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.audience_replace_button = QtWidgets.QPushButton(self.audience_lower_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.audience_replace_button.setFont(font)
        self.audience_replace_button.setStyleSheet("background-color: #202020;")
        self.audience_replace_button.setObjectName("audience_replace_button")
        self.horizontalLayout_27.addWidget(self.audience_replace_button, 0, QtCore.Qt.AlignRight)
        self.audience_add_button = QtWidgets.QPushButton(self.audience_lower_frame)
        self.audience_add_button.setMinimumSize(QtCore.QSize(0, 0))
        self.audience_add_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.audience_add_button.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.audience_add_button.setFont(font)
        self.audience_add_button.setStyleSheet("background-color: #202020;")
        self.audience_add_button.setCheckable(False)
        self.audience_add_button.setAutoDefault(False)
        self.audience_add_button.setObjectName("audience_add_button")
        self.horizontalLayout_27.addWidget(self.audience_add_button, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_13.addWidget(self.audience_lower_frame, 0, QtCore.Qt.AlignBottom)
        self.stackedWidget.addWidget(self.audiences)
        self.categories = QtWidgets.QWidget()
        self.categories.setObjectName("categories")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.categories)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.category_upper_frame = QtWidgets.QFrame(self.categories)
        self.category_upper_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.category_upper_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.category_upper_frame.setObjectName("category_upper_frame")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.category_upper_frame)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.category_window_label = QtWidgets.QLabel(self.category_upper_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.category_window_label.setFont(font)
        self.category_window_label.setObjectName("category_window_label")
        self.horizontalLayout_29.addWidget(self.category_window_label)
        self.category_search_frame = QtWidgets.QFrame(self.category_upper_frame)
        self.category_search_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.category_search_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.category_search_frame.setObjectName("category_search_frame")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.category_search_frame)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.category_lineEdit = QtWidgets.QLineEdit(self.category_search_frame)
        self.category_lineEdit.setStyleSheet("background-color:#69676A;")
        self.category_lineEdit.setObjectName("category_lineEdit")
        self.horizontalLayout_28.addWidget(self.category_lineEdit)
        self.category_search_button = QtWidgets.QPushButton(self.category_search_frame)
        self.category_search_button.setText("")
        self.category_search_button.setIcon(icon12)
        self.category_search_button.setObjectName("category_search_button")
        self.horizontalLayout_28.addWidget(self.category_search_button)
        self.horizontalLayout_29.addWidget(self.category_search_frame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_15.addWidget(self.category_upper_frame, 0, QtCore.Qt.AlignTop)
        self.category_central_frame = QtWidgets.QFrame(self.categories)
        self.category_central_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.category_central_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.category_central_frame.setObjectName("category_central_frame")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.category_central_frame)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.category_tableWidget = QtWidgets.QTableWidget(self.category_central_frame)
        self.category_tableWidget.setObjectName("category_tableWidget")
        self.category_tableWidget.setColumnCount(2)
        self.category_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.category_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.category_tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_16.addWidget(self.category_tableWidget)
        self.verticalLayout_15.addWidget(self.category_central_frame)
        self.category_lower_frame = QtWidgets.QFrame(self.categories)
        self.category_lower_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.category_lower_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.category_lower_frame.setObjectName("category_lower_frame")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.category_lower_frame)
        self.horizontalLayout_30.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_30.setSpacing(50)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.category_replace_button = QtWidgets.QPushButton(self.category_lower_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.category_replace_button.setFont(font)
        self.category_replace_button.setStyleSheet("background-color: #202020;")
        self.category_replace_button.setObjectName("category_replace_button")
        self.horizontalLayout_30.addWidget(self.category_replace_button, 0, QtCore.Qt.AlignRight)
        self.category_add_button = QtWidgets.QPushButton(self.category_lower_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.category_add_button.setFont(font)
        self.category_add_button.setStyleSheet("background-color: #202020;")
        self.category_add_button.setObjectName("category_add_button")
        self.horizontalLayout_30.addWidget(self.category_add_button, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_15.addWidget(self.category_lower_frame, 0, QtCore.Qt.AlignBottom)
        self.stackedWidget.addWidget(self.categories)
        self.subjects = QtWidgets.QWidget()
        self.subjects.setObjectName("subjects")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.subjects)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.subject_upper_frame = QtWidgets.QFrame(self.subjects)
        self.subject_upper_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.subject_upper_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.subject_upper_frame.setObjectName("subject_upper_frame")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.subject_upper_frame)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.subject_window_label = QtWidgets.QLabel(self.subject_upper_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subject_window_label.setFont(font)
        self.subject_window_label.setObjectName("subject_window_label")
        self.horizontalLayout_32.addWidget(self.subject_window_label)
        self.subject_search_frame = QtWidgets.QFrame(self.subject_upper_frame)
        self.subject_search_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.subject_search_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.subject_search_frame.setObjectName("subject_search_frame")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.subject_search_frame)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.subject_lineEdit = QtWidgets.QLineEdit(self.subject_search_frame)
        self.subject_lineEdit.setStyleSheet("background-color: #69676A;")
        self.subject_lineEdit.setObjectName("subject_lineEdit")
        self.horizontalLayout_31.addWidget(self.subject_lineEdit)
        self.subject_search_button = QtWidgets.QPushButton(self.subject_search_frame)
        self.subject_search_button.setText("")
        self.subject_search_button.setIcon(icon12)
        self.subject_search_button.setObjectName("subject_search_button")
        self.horizontalLayout_31.addWidget(self.subject_search_button)
        self.horizontalLayout_32.addWidget(self.subject_search_frame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_17.addWidget(self.subject_upper_frame, 0, QtCore.Qt.AlignTop)
        self.subject_central_frame = QtWidgets.QFrame(self.subjects)
        self.subject_central_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.subject_central_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.subject_central_frame.setObjectName("subject_central_frame")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.subject_central_frame)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.subject_tableWidget = QtWidgets.QTableWidget(self.subject_central_frame)
        self.subject_tableWidget.setObjectName("subject_tableWidget")
        self.subject_tableWidget.setColumnCount(5)
        self.subject_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.subject_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.subject_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.subject_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.subject_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.subject_tableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout_18.addWidget(self.subject_tableWidget)
        self.verticalLayout_17.addWidget(self.subject_central_frame)
        self.subject_lower_frame = QtWidgets.QFrame(self.subjects)
        self.subject_lower_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.subject_lower_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.subject_lower_frame.setObjectName("subject_lower_frame")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.subject_lower_frame)
        self.horizontalLayout_33.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_33.setSpacing(50)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.subject_replace_button = QtWidgets.QPushButton(self.subject_lower_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.subject_replace_button.setFont(font)
        self.subject_replace_button.setStyleSheet("background-color: #202020;")
        self.subject_replace_button.setObjectName("subject_replace_button")
        self.horizontalLayout_33.addWidget(self.subject_replace_button, 0, QtCore.Qt.AlignRight)
        self.subject_add_button = QtWidgets.QPushButton(self.subject_lower_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.subject_add_button.setFont(font)
        self.subject_add_button.setStyleSheet("background-color: #202020;")
        self.subject_add_button.setObjectName("subject_add_button")
        self.horizontalLayout_33.addWidget(self.subject_add_button, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_17.addWidget(self.subject_lower_frame, 0, QtCore.Qt.AlignBottom)
        self.stackedWidget.addWidget(self.subjects)
        self.schedule = QtWidgets.QWidget()
        self.schedule.setObjectName("schedule")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.schedule)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.schedule_upper_frame = QtWidgets.QFrame(self.schedule)
        self.schedule_upper_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.schedule_upper_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.schedule_upper_frame.setObjectName("schedule_upper_frame")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.schedule_upper_frame)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.schedule_window_label = QtWidgets.QLabel(self.schedule_upper_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.schedule_window_label.setFont(font)
        self.schedule_window_label.setObjectName("schedule_window_label")
        self.horizontalLayout_35.addWidget(self.schedule_window_label)
        self.schedule_search_frame = QtWidgets.QFrame(self.schedule_upper_frame)
        self.schedule_search_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.schedule_search_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.schedule_search_frame.setObjectName("schedule_search_frame")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.schedule_search_frame)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.schedule_lineEdit = QtWidgets.QLineEdit(self.schedule_search_frame)
        self.schedule_lineEdit.setStyleSheet("background-color: #69676A;")
        self.schedule_lineEdit.setObjectName("schedule_lineEdit")
        self.horizontalLayout_34.addWidget(self.schedule_lineEdit)
        self.schedule_search_button = QtWidgets.QPushButton(self.schedule_search_frame)
        self.schedule_search_button.setText("")
        self.schedule_search_button.setIcon(icon12)
        self.schedule_search_button.setObjectName("schedule_search_button")
        self.horizontalLayout_34.addWidget(self.schedule_search_button)
        self.horizontalLayout_35.addWidget(self.schedule_search_frame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_19.addWidget(self.schedule_upper_frame)
        self.schedule_central_frame = QtWidgets.QFrame(self.schedule)
        self.schedule_central_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.schedule_central_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.schedule_central_frame.setObjectName("schedule_central_frame")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.schedule_central_frame)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.schedule_tableWidget = QtWidgets.QTableWidget(self.schedule_central_frame)
        self.schedule_tableWidget.setObjectName("schedule_tableWidget")
        self.schedule_tableWidget.setColumnCount(9)
        self.schedule_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.schedule_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule_tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule_tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule_tableWidget.setHorizontalHeaderItem(8, item)
        self.verticalLayout_20.addWidget(self.schedule_tableWidget)
        self.verticalLayout_19.addWidget(self.schedule_central_frame)
        self.schedule_lower_frame = QtWidgets.QFrame(self.schedule)
        self.schedule_lower_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.schedule_lower_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.schedule_lower_frame.setObjectName("schedule_lower_frame")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.schedule_lower_frame)
        self.horizontalLayout_36.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_36.setSpacing(50)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.schedule_replace_button = QtWidgets.QPushButton(self.schedule_lower_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.schedule_replace_button.setFont(font)
        self.schedule_replace_button.setStyleSheet("background-color: #202020;")
        self.schedule_replace_button.setObjectName("schedule_replace_button")
        self.horizontalLayout_36.addWidget(self.schedule_replace_button, 0, QtCore.Qt.AlignRight)
        self.schedule_add_button = QtWidgets.QPushButton(self.schedule_lower_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.schedule_add_button.setFont(font)
        self.schedule_add_button.setStyleSheet("background-color: #202020;")
        self.schedule_add_button.setObjectName("schedule_add_button")
        self.horizontalLayout_36.addWidget(self.schedule_add_button, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_19.addWidget(self.schedule_lower_frame)
        self.stackedWidget.addWidget(self.schedule)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_8.addWidget(self.main_body_frame)
        self.right_central_content_frame = QtWidgets.QFrame(self.central_frame)
        self.right_central_content_frame.setMinimumSize(QtCore.QSize(230, 0))
        self.right_central_content_frame.setMaximumSize(QtCore.QSize(50, 16777215))
        self.right_central_content_frame.setStyleSheet("background-color: #4F4E4F;")  # 246, 98, 121 #30, 97, 139
        self.right_central_content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_central_content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_central_content_frame.setObjectName("right_central_content_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.right_central_content_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.right_central_upper_frame = QtWidgets.QFrame(self.right_central_content_frame)
        self.right_central_upper_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_central_upper_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_central_upper_frame.setObjectName("right_central_upper_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.right_central_upper_frame)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(11, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.about_label = QtWidgets.QLabel(self.right_central_upper_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.about_label.sizePolicy().hasHeightForWidth())
        self.about_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.about_label.setFont(font)
        self.about_label.setMidLineWidth(0)
        self.about_label.setObjectName("about_label")
        self.verticalLayout_3.addWidget(self.about_label, 0, QtCore.Qt.AlignBottom)
        self.about_label.setStyleSheet("background-color: #69676A;")
        self.description_label = QtWidgets.QLabel(self.right_central_upper_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description_label.sizePolicy().hasHeightForWidth())
        self.description_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.description_label.setFont(font)
        self.description_label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.description_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.description_label.setAutoFillBackground(False)
        self.description_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.description_label.setTextFormat(QtCore.Qt.PlainText)
        self.description_label.setObjectName("description_label")
        self.verticalLayout_3.addWidget(self.description_label, 3, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.verticalLayout_2.addWidget(self.right_central_upper_frame, 0, QtCore.Qt.AlignHCenter)
        self.right_central_lower_frame = QtWidgets.QFrame(self.right_central_content_frame)
        self.right_central_lower_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_central_lower_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_central_lower_frame.setObjectName("right_central_lower_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.right_central_lower_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.facebook_frame = QtWidgets.QFrame(self.right_central_lower_frame)
        self.facebook_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.facebook_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.facebook_frame.setObjectName("facebook_frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.facebook_frame)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.facebook_icon_label = QtWidgets.QLabel(self.facebook_frame)
        self.facebook_icon_label.setSizeIncrement(QtCore.QSize(10, 0))
        self.facebook_icon_label.setText("")
        self.facebook_icon_label.setPixmap(QtGui.QPixmap(":/icons/icons/icons8-facebook-circled-30"))
        self.facebook_icon_label.setObjectName("facebook_icon_label")
        self.horizontalLayout_10.addWidget(self.facebook_icon_label, 0, QtCore.Qt.AlignRight)
        self.facebook_link_label = QtWidgets.QLabel(self.facebook_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.facebook_link_label.setFont(font)
        self.facebook_link_label.setOpenExternalLinks(True)
        self.facebook_link_label.setObjectName("facebook_link_label")
        self.horizontalLayout_10.addWidget(self.facebook_link_label, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_4.addWidget(self.facebook_frame, 0, QtCore.Qt.AlignLeft)
        self.source_code_frame = QtWidgets.QFrame(self.right_central_lower_frame)
        self.source_code_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.source_code_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.source_code_frame.setObjectName("source_code_frame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.source_code_frame)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.source_code_label = QtWidgets.QLabel(self.source_code_frame)
        self.source_code_label.setText("")
        self.source_code_label.setPixmap(QtGui.QPixmap(":/icons/icons/icons8-source-code-30.png"))
        self.source_code_label.setOpenExternalLinks(True)
        self.source_code_label.setObjectName("source_code_label")
        self.horizontalLayout_11.addWidget(self.source_code_label, 0, QtCore.Qt.AlignRight)
        self.source_code_link_label = QtWidgets.QLabel(self.source_code_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.source_code_link_label.setFont(font)
        self.source_code_link_label.setOpenExternalLinks(True)
        self.source_code_link_label.setObjectName("source_code_link_label")
        self.horizontalLayout_11.addWidget(self.source_code_link_label, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_4.addWidget(self.source_code_frame, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_2.addWidget(self.right_central_lower_frame, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_8.addWidget(self.right_central_content_frame)
        self.verticalLayout.addWidget(self.central_frame)
        self.footer_frame = QtWidgets.QFrame(self.centralwidget)
        self.footer_frame.setStyleSheet("background-color: #4F4E4F;")
        self.footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer_frame.setObjectName("footer_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.footer_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.footer_left_frame = QtWidgets.QFrame(self.footer_frame)
        self.footer_left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer_left_frame.setObjectName("footer_left_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.footer_left_frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.version_label = QtWidgets.QLabel(self.footer_left_frame)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.version_label.setFont(font)
        self.version_label.setObjectName("version_label")
        self.horizontalLayout_6.addWidget(self.version_label, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        self.horizontalLayout_5.addWidget(self.footer_left_frame)
        self.footer_right_frame = QtWidgets.QFrame(self.footer_frame)
        self.footer_right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer_right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer_right_frame.setObjectName("footer_right_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.footer_right_frame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.help_button = QtWidgets.QPushButton(self.footer_right_frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.help_button.setFont(font)
        self.help_button.setObjectName("help_button")
        self.horizontalLayout_7.addWidget(self.help_button)
        self.horizontalLayout_5.addWidget(self.footer_right_frame, 0, QtCore.Qt.AlignRight)
        self.size_grip = QtWidgets.QFrame(self.footer_frame)
        self.size_grip.setMinimumSize(QtCore.QSize(10, 10))
        self.size_grip.setMaximumSize(QtCore.QSize(10, 10))
        self.size_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.size_grip.setObjectName("size_grip")
        self.horizontalLayout_5.addWidget(self.size_grip, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.footer_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        ###########
        self.header_left_frame.setStyleSheet("padding: 0;"
                                             "margin: 0;")
        self.menu_button.setStyleSheet("margin: 0;")
        ###########

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_label.setText(_translate("MainWindow", "Menu"))
        self.app_name_label.setText(_translate("MainWindow", " DATA  MANAGER"))
        self.student_label.setText(_translate("MainWindow", "Students"))
        self.group_label.setText(_translate("MainWindow", "Groups"))
        self.staff_label.setText(_translate("MainWindow", "Staff"))
        self.instructor_label.setText(_translate("MainWindow", "Instructors"))
        self.audience_label.setText(_translate("MainWindow", "Audiences"))
        self.category_label.setText(_translate("MainWindow", "Categories"))
        self.subject_label.setText(_translate("MainWindow", "Subjects"))
        self.schedule_label.setText(_translate("MainWindow", "Schedules"))
        self.student_window_label.setText(_translate("MainWindow", "Students"))
        self.student_lineEdit.setText(_translate("MainWindow", "Search Student"))
        item = self.student_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Student_ID"))
        item = self.student_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.student_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last_Name"))
        item = self.student_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Patronymic"))
        item = self.student_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Birth_Date"))
        item = self.student_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Address"))
        item = self.student_tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Phone_Number"))
        item = self.student_tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Email"))
        item = self.student_tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Passport_ID"))
        self.student_tableWidget.setColumnWidth(0, 170)
        self.student_tableWidget.setColumnWidth(1, 170)
        self.student_tableWidget.setColumnWidth(2, 170)
        self.student_tableWidget.setColumnWidth(3, 170)
        self.student_tableWidget.setColumnWidth(4, 170)
        self.student_tableWidget.setColumnWidth(5, 250)
        self.student_tableWidget.setColumnWidth(6, 170)
        self.student_tableWidget.setColumnWidth(7, 250)
        self.student_tableWidget.setColumnWidth(8, 170)
        self.student_tableWidget.horizontalHeaderItem(8).setSizeHint(QtCore.QSize(0,100))
        self.student_replace_button.setText(_translate("MainWindow", "Update"))
        self.student_add_button.setText(_translate("MainWindow", "Add"))
        self.group_window_label.setText(_translate("MainWindow", "Groups"))
        self.group_lineEdit.setText(_translate("MainWindow", "Search Group"))
        self.group_tableWidget.setSortingEnabled(False)
        item = self.group_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Group_ID"))
        item = self.group_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title"))
        self.group_tableWidget.setColumnWidth(0, 170)
        self.group_tableWidget.setColumnWidth(1, 170)
        self.group_tableWidget.horizontalHeaderItem(1).setSizeHint(QtCore.QSize(0,100))
        self.group_replace_button.setText(_translate("MainWindow", "Update"))
        self.group_add_button.setText(_translate("MainWindow", "Add"))
        self.staff_window_label.setText(_translate("MainWindow", "Staff"))
        self.staff_lineEdit.setText(_translate("MainWindow", "Search Staff"))
        item = self.staff_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Staff_ID"))
        item = self.staff_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.staff_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last_Name"))
        item = self.staff_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Patronymic"))
        item = self.staff_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Education"))
        item = self.staff_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Address"))
        item = self.staff_tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Phone_Number"))
        item = self.staff_tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Email"))
        item = self.staff_tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Position"))
        self.staff_tableWidget.setColumnWidth(0, 170)
        self.staff_tableWidget.setColumnWidth(1, 170)
        self.staff_tableWidget.setColumnWidth(2, 170)
        self.staff_tableWidget.setColumnWidth(3, 170)
        self.staff_tableWidget.setColumnWidth(4, 170)
        self.staff_tableWidget.setColumnWidth(5, 170)
        self.staff_tableWidget.setColumnWidth(6, 170)
        self.staff_tableWidget.setColumnWidth(7, 250)
        self.staff_tableWidget.setColumnWidth(8, 250)
        self.staff_tableWidget.horizontalHeaderItem(8).setSizeHint(QtCore.QSize(0,100))
        self.staff_replace_button.setText(_translate("MainWindow", "Update"))
        self.staff_add_button.setText(_translate("MainWindow", "Add"))
        self.instructor_window_label.setText(_translate("MainWindow", "Instructors"))
        self.instructor_lineEdit.setText(_translate("MainWindow", "Search Instructor"))
        item = self.instructor_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Instructor_ID"))
        item = self.instructor_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Staff"))
        item = self.instructor_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description"))
        item = self.instructor_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Teaching_Object"))
        self.instructor_tableWidget.setColumnWidth(0, 170)
        self.instructor_tableWidget.setColumnWidth(1, 170)
        self.instructor_tableWidget.setColumnWidth(2, 300)
        self.instructor_tableWidget.setColumnWidth(3, 170)
        self.instructor_tableWidget.horizontalHeaderItem(3).setSizeHint(QtCore.QSize(0,100))
        self.instructor_replace_button.setText(_translate("MainWindow", "Update"))
        self.instructor_add_button.setText(_translate("MainWindow", "Add"))
        self.audience_window_label.setText(_translate("MainWindow", "Audiences"))
        self.audience_lineEdit.setText(_translate("MainWindow", "Search Audience"))
        item = self.audience_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Audience_ID"))
        item = self.audience_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title"))
        item = self.audience_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Seat_Count"))
        item = self.audience_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Computer_Count"))
        self.audience_tableWidget.setColumnWidth(0, 170)
        self.audience_tableWidget.setColumnWidth(1, 170)
        self.audience_tableWidget.setColumnWidth(2, 170)
        self.audience_tableWidget.setColumnWidth(3, 170)
        self.audience_tableWidget.horizontalHeaderItem(3).setSizeHint(QtCore.QSize(0,100))
        self.audience_replace_button.setText(_translate("MainWindow", "Update"))
        self.audience_add_button.setText(_translate("MainWindow", "Add"))
        self.category_window_label.setText(_translate("MainWindow", "Categories"))
        self.category_lineEdit.setText(_translate("MainWindow", "Search Category"))
        item = self.category_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Category_ID"))
        item = self.category_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Subject_Category"))
        self.category_tableWidget.setColumnWidth(0,170)
        self.category_tableWidget.setColumnWidth(1,200)
        self.category_tableWidget.horizontalHeaderItem(1).setSizeHint(QtCore.QSize(0,100))
        self.category_replace_button.setText(_translate("MainWindow", "Update"))
        self.category_add_button.setText(_translate("MainWindow", "Add"))
        self.subject_window_label.setText(_translate("MainWindow", "Subjects"))
        self.subject_lineEdit.setText(_translate("MainWindow", "Search Subject"))
        item = self.subject_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Subject_ID"))
        item = self.subject_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Category"))
        item = self.subject_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Title"))
        item = self.subject_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Description"))
        item = self.subject_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Price"))
        self.subject_tableWidget.setColumnWidth(0,170)
        self.subject_tableWidget.setColumnWidth(1,170)
        self.subject_tableWidget.setColumnWidth(2,170)
        self.subject_tableWidget.setColumnWidth(3,300)
        self.subject_tableWidget.setColumnWidth(4,170)
        self.subject_tableWidget.horizontalHeaderItem(4).setSizeHint(QtCore.QSize(0,100))
        self.subject_replace_button.setText(_translate("MainWindow", "Update"))
        self.subject_add_button.setText(_translate("MainWindow", "Add"))
        self.schedule_window_label.setText(_translate("MainWindow", "Schedules"))
        self.schedule_lineEdit.setText(_translate("MainWindow", "Search Schedule"))
        self.schedule_tableWidget.setColumnWidth(0, 170)
        self.schedule_tableWidget.setColumnWidth(1, 170)
        self.schedule_tableWidget.setColumnWidth(2, 170)
        self.schedule_tableWidget.setColumnWidth(3, 170)
        self.schedule_tableWidget.setColumnWidth(4, 170)
        self.schedule_tableWidget.setColumnWidth(5, 170)
        self.schedule_tableWidget.setColumnWidth(6, 170)
        self.schedule_tableWidget.setColumnWidth(7, 170)
        self.schedule_tableWidget.setColumnWidth(8, 300)
        self.schedule_tableWidget.horizontalHeaderItem(8).setSizeHint(QtCore.QSize(0,100))
        item = self.schedule_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Schedule_ID"))
        item = self.schedule_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Group"))
        item = self.schedule_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Instructor"))
        item = self.schedule_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Subject"))
        item = self.schedule_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Audience"))
        item = self.schedule_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Learming_Type"))
        item = self.schedule_tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Start_Date"))
        item = self.schedule_tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Finish_Date"))
        item = self.schedule_tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Time_Schedule"))
        self.schedule_replace_button.setText(_translate("MainWindow", "Update"))
        self.schedule_add_button.setText(_translate("MainWindow", "Add"))
        self.description_label.setStyleSheet("background-color: #69676A;")
        self.about_label.setText(_translate("MainWindow", "\nAbout"))
        self.description_label.setText(_translate("MainWindow", "App designed and developed\n"
                                                  "by ColoAi Art Int. ColoAi is\n"
                                                  "a startup company with artifi - \n"
                                                  "cial inteligence solutions.\n\n"))
        self.facebook_link_label.setText(_translate("MainWindow", "<a href=\"https://www.facebook.com/ColoArtInt\">Facebook</a>"))
        self.source_code_link_label.setText(_translate("MainWindow", "<a href=\"https://github.com/00kar/DataManager\">Source code</a>"))
        self.version_label.setText(_translate("MainWindow", "Version 1.1 | Copyright ColoAi Co."))
        self.help_button.setText(_translate("MainWindow", "Help"))
